# -*- coding: utf-8 -*-
"""studyperformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXcX3WEj1nBsATR1TY7WMxerLpPfAp7s
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#sample dataset
data = {
    'StudyHours': [1, 2, 3, 4, 5, 6, 7, 8, 2, 5],
    'Attendance': [50, 60, 65, 70, 80, 85, 90, 95, 55, 88],
    'Assignments': ['No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes'],
    'Performance': ['Low', 'Low', 'Medium', 'Medium', 'High', 'High', 'High', 'High', 'Low', 'High']
}

df = pd.DataFrame(data)


le = LabelEncoder()

df['Assignments'] = le.fit_transform(df['Assignments'])
df['Performance'] = le.fit_transform(df['Performance'])

# Input and Output
X = df[['StudyHours', 'Attendance', 'Assignments']]
y = df['Performance']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Model
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)


# Test Accuracy
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)


# User Input
print("\n--- Student Performance Prediction ---")

study_hours = float(input("Enter study hours: "))
attendance = int(input("Enter attendance percentage: "))

assignment = input("Assignments completed? (Yes/No): ")

assignment_encoded = le.fit_transform([assignment])[0]


# Prediction

prediction = model.predict([[study_hours, attendance, assignment_encoded]])

# Convert prediction back to text
performance_labels = ['High', 'Low', 'Medium']

print("\nPredicted Performance:", performance_labels[prediction[0]])